[2021-10-14 14:40:12,842] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2021-10-13T00:00:00+00:00 [queued]>
[2021-10-14 14:40:12,856] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2021-10-13T00:00:00+00:00 [queued]>
[2021-10-14 14:40:12,856] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 14:40:12,857] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-10-14 14:40:12,857] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 14:40:12,875] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): inaccurate> on 2021-10-13 00:00:00+00:00
[2021-10-14 14:40:12,880] {standard_task_runner.py:52} INFO - Started process 12693 to run task
[2021-10-14 14:40:12,887] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2021-10-13T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpz3wo9762', '--error-file', '/tmp/tmpryhhcx7p']
[2021-10-14 14:40:12,889] {standard_task_runner.py:77} INFO - Job 27: Subtask inaccurate
[2021-10-14 14:40:12,934] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2021-10-13T00:00:00+00:00 [running]> on host user-Latitude-3410
[2021-10-14 14:40:12,976] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2021-10-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-13T00:00:00+00:00
[2021-10-14 14:40:12,977] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-10-14 14:40:12,978] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2021-10-14 14:40:12,986] {subprocess.py:85} INFO - Output:
[2021-10-14 14:40:12,987] {subprocess.py:89} INFO - inaccurate
[2021-10-14 14:40:12,987] {subprocess.py:93} INFO - Command exited with return code 0
[2021-10-14 14:40:13,016] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20211013T000000, start_date=20211014T091012, end_date=20211014T091013
[2021-10-14 14:40:13,059] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-14 14:40:13,081] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-10-14 14:40:16,309] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2021-10-14T09:09:53.722625+00:00 [queued]>
[2021-10-14 14:40:16,325] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2021-10-14T09:09:53.722625+00:00 [queued]>
[2021-10-14 14:40:16,325] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 14:40:16,325] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-10-14 14:40:16,325] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 14:40:16,339] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): inaccurate> on 2021-10-14 09:09:53.722625+00:00
[2021-10-14 14:40:16,342] {standard_task_runner.py:52} INFO - Started process 12725 to run task
[2021-10-14 14:40:16,346] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2021-10-14T09:09:53.722625+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpem1r1k2r', '--error-file', '/tmp/tmp74vbllqq']
[2021-10-14 14:40:16,348] {standard_task_runner.py:77} INFO - Job 28: Subtask inaccurate
[2021-10-14 14:40:16,380] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.inaccurate manual__2021-10-14T09:09:53.722625+00:00 [running]> on host user-Latitude-3410
[2021-10-14 14:40:16,420] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2021-10-14T09:09:53.722625+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-14T09:09:53.722625+00:00
[2021-10-14 14:40:16,421] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-10-14 14:40:16,422] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2021-10-14 14:40:16,428] {subprocess.py:85} INFO - Output:
[2021-10-14 14:40:16,429] {subprocess.py:89} INFO - inaccurate
[2021-10-14 14:40:16,430] {subprocess.py:93} INFO - Command exited with return code 0
[2021-10-14 14:40:16,452] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20211014T090953, start_date=20211014T091016, end_date=20211014T091016
[2021-10-14 14:40:16,479] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-14 14:40:16,499] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-10-14 14:47:45,107] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2021-10-14T09:17:34.915835+00:00 [queued]>
[2021-10-14 14:47:45,120] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2021-10-14T09:17:34.915835+00:00 [queued]>
[2021-10-14 14:47:45,120] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 14:47:45,120] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-10-14 14:47:45,120] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 14:47:45,131] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): inaccurate> on 2021-10-14 09:17:34.915835+00:00
[2021-10-14 14:47:45,132] {standard_task_runner.py:52} INFO - Started process 15173 to run task
[2021-10-14 14:47:45,135] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2021-10-14T09:17:34.915835+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpeszalf18', '--error-file', '/tmp/tmpa1m4o6sn']
[2021-10-14 14:47:45,136] {standard_task_runner.py:77} INFO - Job 34: Subtask inaccurate
[2021-10-14 14:47:45,169] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.inaccurate manual__2021-10-14T09:17:34.915835+00:00 [running]> on host user-Latitude-3410
[2021-10-14 14:47:45,197] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2021-10-14T09:17:34.915835+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-14T09:17:34.915835+00:00
[2021-10-14 14:47:45,198] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-10-14 14:47:45,198] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2021-10-14 14:47:45,207] {subprocess.py:85} INFO - Output:
[2021-10-14 14:47:45,208] {subprocess.py:89} INFO - inaccurate
[2021-10-14 14:47:45,208] {subprocess.py:93} INFO - Command exited with return code 0
[2021-10-14 14:47:45,222] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20211014T091734, start_date=20211014T091745, end_date=20211014T091745
[2021-10-14 14:47:45,271] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-14 14:47:45,283] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
