[2021-11-19 11:19:52,259] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: Outstanding_resport.get_excel scheduled__2021-11-18T00:00:00+00:00 [queued]>
[2021-11-19 11:19:52,316] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: Outstanding_resport.get_excel scheduled__2021-11-18T00:00:00+00:00 [queued]>
[2021-11-19 11:19:52,317] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-19 11:19:52,317] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-11-19 11:19:52,317] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-19 11:19:52,342] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): get_excel> on 2021-11-18 00:00:00+00:00
[2021-11-19 11:19:52,359] {standard_task_runner.py:52} INFO - Started process 24839 to run task
[2021-11-19 11:19:52,365] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Outstanding_resport', 'get_excel', 'scheduled__2021-11-18T00:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/outstanding_report.py', '--cfg-path', '/tmp/tmp3nl_u5lw', '--error-file', '/tmp/tmpgckqruk_']
[2021-11-19 11:19:52,370] {standard_task_runner.py:77} INFO - Job 79: Subtask get_excel
[2021-11-19 11:19:52,450] {logging_mixin.py:109} INFO - Running <TaskInstance: Outstanding_resport.get_excel scheduled__2021-11-18T00:00:00+00:00 [running]> on host user-Latitude-3410
[2021-11-19 11:19:52,541] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=shindesushant818@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Outstanding_resport
AIRFLOW_CTX_TASK_ID=get_excel
AIRFLOW_CTX_EXECUTION_DATE=2021-11-18T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-18T00:00:00+00:00
[2021-11-19 11:19:52,666] {transport.py:1819} INFO - Connected (version 2.0, client OpenSSH_for_Windows_7.7)
[2021-11-19 11:19:52,920] {transport.py:1819} INFO - Authentication (publickey) failed.
[2021-11-19 11:19:53,017] {transport.py:1819} INFO - Authentication (publickey) failed.
[2021-11-19 11:19:53,084] {transport.py:1819} INFO - Authentication (password) successful!
[2021-11-19 11:19:53,272] {sftp.py:158} INFO - [chan 0] Opened sftp connection (server version 3)
[2021-11-19 11:19:55,403] {sftp.py:158} INFO - [chan 0] sftp session closed.
[2021-11-19 11:19:55,404] {python.py:152} INFO - Done. Returned value was: None
[2021-11-19 11:19:55,430] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=Outstanding_resport, task_id=get_excel, execution_date=20211118T000000, start_date=20211119T054952, end_date=20211119T054955
[2021-11-19 11:19:55,476] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-19 11:19:55,536] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-11-19 11:20:02,882] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: Outstanding_resport.get_excel manual__2021-11-19T05:49:42.522615+00:00 [queued]>
[2021-11-19 11:20:02,910] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: Outstanding_resport.get_excel manual__2021-11-19T05:49:42.522615+00:00 [queued]>
[2021-11-19 11:20:02,910] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-19 11:20:02,910] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-11-19 11:20:02,911] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-19 11:20:02,936] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): get_excel> on 2021-11-19 05:49:42.522615+00:00
[2021-11-19 11:20:02,942] {standard_task_runner.py:52} INFO - Started process 25109 to run task
[2021-11-19 11:20:02,946] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Outstanding_resport', 'get_excel', 'manual__2021-11-19T05:49:42.522615+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/outstanding_report.py', '--cfg-path', '/tmp/tmpccm4_uha', '--error-file', '/tmp/tmp1l976fj1']
[2021-11-19 11:20:02,951] {standard_task_runner.py:77} INFO - Job 80: Subtask get_excel
[2021-11-19 11:20:03,023] {logging_mixin.py:109} INFO - Running <TaskInstance: Outstanding_resport.get_excel manual__2021-11-19T05:49:42.522615+00:00 [running]> on host user-Latitude-3410
[2021-11-19 11:20:03,092] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=shindesushant818@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Outstanding_resport
AIRFLOW_CTX_TASK_ID=get_excel
AIRFLOW_CTX_EXECUTION_DATE=2021-11-19T05:49:42.522615+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-19T05:49:42.522615+00:00
[2021-11-19 11:20:03,205] {transport.py:1819} INFO - Connected (version 2.0, client OpenSSH_for_Windows_7.7)
[2021-11-19 11:20:03,548] {transport.py:1819} INFO - Authentication (publickey) failed.
[2021-11-19 11:20:03,653] {transport.py:1819} INFO - Authentication (publickey) failed.
[2021-11-19 11:20:03,878] {transport.py:1819} INFO - Authentication (password) successful!
[2021-11-19 11:20:04,268] {sftp.py:158} INFO - [chan 0] Opened sftp connection (server version 3)
[2021-11-19 11:20:08,232] {sftp.py:158} INFO - [chan 0] sftp session closed.
[2021-11-19 11:20:08,233] {python.py:152} INFO - Done. Returned value was: None
[2021-11-19 11:20:08,255] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=Outstanding_resport, task_id=get_excel, execution_date=20211119T054942, start_date=20211119T055002, end_date=20211119T055008
[2021-11-19 11:20:08,331] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-19 11:20:08,434] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
