[2021-11-19 10:40:31,198] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.put_excel scheduled__2021-11-04T00:00:00+00:00 [queued]>
[2021-11-19 10:40:31,306] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: file_upload.put_excel scheduled__2021-11-04T00:00:00+00:00 [queued]>
[2021-11-19 10:40:31,307] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-19 10:40:31,307] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-11-19 10:40:31,307] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-19 10:40:31,364] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): put_excel> on 2021-11-04 00:00:00+00:00
[2021-11-19 10:40:31,388] {standard_task_runner.py:52} INFO - Started process 10969 to run task
[2021-11-19 10:40:31,389] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'file_upload', 'put_excel', 'scheduled__2021-11-04T00:00:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/file_loadin.py', '--cfg-path', '/tmp/tmpm_wtfy_o', '--error-file', '/tmp/tmp7dyxbrod']
[2021-11-19 10:40:31,415] {standard_task_runner.py:77} INFO - Job 65: Subtask put_excel
[2021-11-19 10:40:31,642] {logging_mixin.py:109} INFO - Running <TaskInstance: file_upload.put_excel scheduled__2021-11-04T00:00:00+00:00 [running]> on host user-Latitude-3410
[2021-11-19 10:40:31,838] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=file_upload
AIRFLOW_CTX_TASK_ID=put_excel
AIRFLOW_CTX_EXECUTION_DATE=2021-11-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-04T00:00:00+00:00
[2021-11-19 10:40:31,906] {transport.py:1819} INFO - Connected (version 2.0, client OpenSSH_7.4)
[2021-11-19 10:40:32,114] {transport.py:1819} INFO - Auth banner: b'Authorized uses only. All activity may be monitored and reported.\n'
[2021-11-19 10:40:32,115] {transport.py:1819} INFO - Authentication (publickey) failed.
[2021-11-19 10:40:32,400] {transport.py:1819} INFO - Authentication (publickey) failed.
[2021-11-19 10:40:32,472] {transport.py:1819} INFO - Authentication (password) successful!
[2021-11-19 10:40:40,022] {sftp.py:158} INFO - [chan 0] Opened sftp connection (server version 3)
[2021-11-19 10:40:40,268] {logging_mixin.py:109} INFO - [Errno 2] No such file
[2021-11-19 10:40:40,269] {python.py:152} INFO - Done. Returned value was: None
[2021-11-19 10:40:40,319] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=file_upload, task_id=put_excel, execution_date=20211104T000000, start_date=20211119T051031, end_date=20211119T051040
[2021-11-19 10:40:40,462] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-19 10:40:40,618] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
